name: Exemplo de Extração de API em Python e JavaScript

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Configurar ambiente Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 

    - name: Ativar ambiente virtual Python
      run: |
        python -m venv venv
        source venv/bin/activate 

    - name: Instalar dependências Python
      run: |
        pip install -r requirements.txt  

    - name: Instalar dependências JavaScript
      run: |
        cd exer.02
        npm install

    - name: Definir variável de ambiente POKEMON_FILES_PATH
      run: echo "POKEMON_FILES_PATH=pokemon_files" >> $GITHUB_ENV
    
    - name: Definir variável de ambiente EXER_FILES_PATH
      run: echo "EXER_FILES_PATH=pokemon_files" >> $GITHUB_ENV  

    - name: Executar scripts
      run: |
        python pokemon.py
        python exer.01.py
        node exerc.02.js
